# Generated by Django 4.1.5 on 2023-01-23 02:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=9999999)),
                ('DateTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
