# Generated by Django 4.1.5 on 2023-01-23 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Poset',
            new_name='Post',
        ),
    ]
